version: '3.8'

services:
  eep:
    build:
      context: ./EEP
    ports:
      - "8000:8000"
    environment:
      - RUNNING_IN_DOCKER=true
      - IEP1_URL=http://iep1:5001
      - IEP2_URL=http://iep2:5002
      - IEP3_URL=http://iep3:5003
    depends_on:
      - iep1
      - iep2
      - iep3

  iep1:
    build:
      context: ./IEP1_binary_human_detection
    expose:
      - "5001"
    volumes:
      - ./IEP1_binary_human_detection/models:/workspace/models

  iep2:
    build:
      context: ./IEP2_shoplifting_detection/predict
    expose:
      - "5002"
    volumes:
      - ./IEP2_shoplifting_detection/data/unsupervised:/data/unsupervised
      - ./IEP2_shoplifting_detection/mlruns:/app/mlruns

  iep3:
    build:
      context: ./IEP3_human_detection
    expose:
      - "5003"
    volumes:
      - ./IEP3_human_detection/runs:/app/runs
