version: '3.8'

services:
  eep:
    image: jadshaker/eece-503n-project-eep:latest
    ports:
      - '8000:8000'
    environment:
      - RUNNING_IN_DOCKER=true
      - IEP1_URL=http://iep1:5001
      - IEP2_URL=http://iep2:5002
    depends_on:
      - iep1
      - iep2

  iep1:
    image: jadshaker/eece-503n-project-iep1:latest
    expose:
      - '5001'
    volumes:
      - ./IEP1_binary_human_detection/models:/workspace/models

  iep2:
    image: jadshaker/eece-503n-project-iep2:latest
    expose:
      - '5002'
    volumes:
      - ./data/unsupervised:/data/unsupervised
      - ./mlruns:/app/mlruns

  prometheus:
    image: prom/prometheus:latest
    ports:
      - '9090:9090'
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    depends_on:
      - eep
      - iep1
      - iep2

  grafana:
    image: grafana/grafana:latest
    ports:
      - '3000:3000'
    volumes:
      - ./grafana/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/dashboard-data:/var/lib/grafana/dashboards
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_INSTALL_PLUGINS=grafana-piechart-panel
    depends_on:
      - prometheus
