services:
  ui:
    build:
      context: ./ui
    ports:
      - '80:80'
    depends_on:
      - eep
      - file-hosting

  file-hosting:
    build:
      context: ./file_hosting
    ports:
      - '9000:9000'
    volumes:
      - ./CCTV:/CCTV

  eep:
    build:
      context: ./EEP
    ports:
      - '8000:8000'
    environment:
      - RUNNING_IN_DOCKER=true
      - IEP1_URL=http://iep1:5001
      - IEP2_URL=http://iep2:5002
    volumes:
      - ./data:/app/data
    depends_on:
      - iep1
      - iep2
    expose:
      - '8000'

  iep1:
    build:
      context: ./IEP1_binary_human_detection
    expose:
      - '5001'

  iep2:
    build:
      context: ./IEP2_shoplifting_detection/predict
    expose:
      - '5002'
    volumes:
      - ./mlruns:/app/mlruns

  prometheus:
    image: prom/prometheus:latest
    ports:
      - '9090:9090'
    volumes:
      - ./k3s/monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    depends_on:
      - eep
      - iep1
      - iep2

  grafana:
    image: grafana/grafana:latest
    ports:
      - '3000:3000'
    volumes:
      - ./k3s/monitoring/grafana/datasources:/etc/grafana/provisioning/datasources
      - ./k3s/monitoring/grafana/dashboards:/etc/grafana/provisioning/dashboards
      - ./k3s/monitoring/grafana/dashboard-data:/var/lib/grafana/dashboards
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_INSTALL_PLUGINS=grafana-piechart-panel
    depends_on:
      - prometheus
