apiVersion: apps/v1
kind: Deployment
metadata:
  name: iep1-deployment
  namespace: shoplift
spec:
  replicas: 4
  selector:
    matchLabels:
      app: iep1
  template:
    metadata:
      labels:
        app: iep1
    spec:
      containers:
        - name: iep1
          image: jadshaker/iep1:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5001
          readinessProbe:
            httpGet:
              path: /health
              port: 5001
            initialDelaySeconds: 5
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: iep1
  namespace: shoplift
spec:
  selector:
    app: iep1
  ports:
    - port: 5001
      targetPort: 5001
  type: ClusterIP
