apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui-deployment
  namespace: shoplift
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ui
  template:
    metadata:
      labels:
        app: ui
    spec:
      containers:
        - name: ui
          image: jadshaker/ui:latest
          imagePullPolicy: Always
          env:
            - name: REACT_APP_EEP_URL
              value: 'http://eep-service:8000'
            - name: REACT_APP_FILE_SERVER_URL
              value: 'http://file-hosting-service:9000'
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: ui-service
  namespace: shoplift
spec:
  selector:
    app: ui
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30090
