global:
  # Default sampling FPS for EEP process-video: 4
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'eep'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['eep:8000']

  - job_name: 'iep1_binary_human_detection'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['iep1:5001']

  - job_name: 'iep2_shoplifting_detection'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['iep2:5002']
