apiVersion: apps/v1
kind: Deployment
metadata:
  name: iep2
  namespace: eece-503n
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iep2
  template:
    metadata:
      labels:
        app: iep2
    spec:
      containers:
      - name: iep2
        image: jadshaker/iep2-predict:latest
        ports:
        - containerPort: 5002
        volumeMounts:
        - name: mlruns
          mountPath: /app/mlruns
        resources:
          limits:
            memory: "4Gi"  # Increased for ML model loading
            cpu: "2"       # Increased for ML inference
          requests:
            memory: "2Gi"  # Increased minimum memory
            cpu: "1"       # Increased minimum CPU
      volumes:
      - name: mlruns
        hostPath:
          path: /home/hisham/Desktop/503n/EECE-503N-Project/IEP2_shoplifting_detection/train/mlruns
          type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: iep2
  namespace: eece-503n
spec:
  selector:
    app: iep2
  ports:
  - port: 5002
    targetPort: 5002
  type: ClusterIP
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: iep2-hpa
  namespace: eece-503n
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: iep2
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70