apiVersion: apps/v1
kind: Deployment
metadata:
  name: eep
  namespace: eece-503n
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eep
  template:
    metadata:
      labels:
        app: eep
    spec:
      containers:
      - name: eep
        image: jadshaker/eep:latest
        ports:
        - containerPort: 8000
        env:
        - name: RUNNING_IN_DOCKER
          value: "true"
        - name: IEP1_URL
          value: "http://iep1.eece-503n.svc.cluster.local:5001"
        - name: IEP2_URL
          value: "http://iep2.eece-503n.svc.cluster.local:5002"
        volumeMounts:
        - name: unconfirmed-data
          mountPath: /app/data/unconfirmed
        - name: confirmed-data
          mountPath: /app/data/confirmed
        resources:
          limits:
            memory: "2Gi"  # Increased memory limit
            cpu: "1"       # Increased CPU limit
          requests:
            memory: "1Gi"  # Increased memory request 
            cpu: "500m"    # Increased CPU request
      volumes:
      - name: unconfirmed-data
        hostPath:
          path: /home/hisham/Desktop/503n/EECE-503N-Project/data/unconfirmed
          type: DirectoryOrCreate
      - name: confirmed-data
        hostPath:
          path: /home/hisham/Desktop/503n/EECE-503N-Project/data/confirmed
          type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: eep
  namespace: eece-503n
spec:
  selector:
    app: eep
  ports:
  - port: 8000
    targetPort: 8000
  type: NodePort
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: eep-hpa
  namespace: eece-503n
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: eep
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70