apiVersion: batch/v1
kind: CronJob
metadata:
  name: iep2-retrain
  namespace: eece-503n
spec:
  schedule: "0 0 */14 * *" # Runs at 00:00 every 14 days
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: iep2-train
            image: jadshaker/iep2-train:latest # <-- IMPORTANT: Replace with your actual training image name if different
            imagePullPolicy: Always # Ensure the latest image is pulled
            volumeMounts:
            - name: mlruns
              mountPath: /app/mlruns # Mount path for model artifacts
            - name: dataset
              mountPath: /data      # Mount path for the dataset
            # Add environment variables if needed by your training script
            # env:
            # - name: DATA_PATH
            #   value: "/path/to/data" # Example
            resources:
              # Adjust resource requests and limits based on training needs
              requests:
                memory: "16Gi" # Increased request
                cpu: "4"       # Increased request
              limits:
                memory: "32Gi" # Increased limit
                cpu: "8"       # Increased limit
          volumes:
          - name: mlruns
            persistentVolumeClaim:
              claimName: mlruns-pvc # Use the existing PVC for model artifacts
          - name: dataset
            persistentVolumeClaim:
              claimName: dataset-pvc # Use the new PVC for the dataset
          restartPolicy: OnFailure # Restart policy for the job pod
