apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dataset-pvc
  namespace: eece-503n
spec:
  accessModes:
    - ReadWriteMany # Or ReadWriteOnce if only one pod needs write access at a time
  resources:
    requests:
      storage: 10Gi # Allocate space for the dataset (adjust if needed)
  storageClassName: local-storage # Assuming same storage class as mlruns-pvc
