name: Build and Push IEP1 Docker Image

on:
  push:
    branches: [main]
    paths:
      - 'IEP1_binary_human_detection'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push IEP1 image
        uses: docker/build-push-action@v4
        with:
          context: ./IEP1_binary_human_detection
          file: ./IEP1_binary_human_detection/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/iep1:latest
