name: Build and Push UI Docker Image

on:
  push:
    branches: [main]
    paths:
      - 'ui/**'
      - .github/workflows/build-ui.yml

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build UI image
        run: |
          docker build \
          --build-arg REACT_APP_EEP_URL=http://localhost:30080 \
          --build-arg REACT_APP_FILE_SERVER_URL=http://localhost:31000 \
          -t ${{ secrets.DOCKERHUB_USERNAME }}/ui:latest ./ui

      - name: Push UI image to Docker Hub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/ui:latest
