name: Build and Push File-Hosting Docker Image

on:
  push:
    branches: [main]
    paths:
      - 'file_hosting/**'
      - .github/workflows/build-file-hosting.yml

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push File Hosting image
        uses: docker/build-push-action@v4
        with:
          context: ./file_hosting
          file: ./file_hosting/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/file-hosting:latest
