name: Build and Push IEP2 Training Docker Image

on:
  push:
    branches: [main]
    paths:
      - 'IEP2_shoplifting_detection/train/**'
      - .github/workflows/build-iep2-train.yml

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push IEP2 training image
        uses: docker/build-push-action@v4
        with:
          context: ./IEP2_shoplifting_detection/train
          file: ./IEP2_shoplifting_detection/train/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/iep2-train:latest
