name: Build and Push UI Docker Image

on:
  push:
    branches: [main]
    paths:
      - 'ui/**'
      - .github/workflows/build-ui.yml

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push UI image
        uses: docker/build-push-action@v4
        with:
          context: ./ui
          file: ./ui/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/ui:latest
