name: PR Health Check

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
    paths:
      - .github/workflows/pr-health-check.yml

jobs:
  health_check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install gdown (Google-Drive CLI downloader)
        run: pip install --no-cache-dir gdown

      - name: Download experiment artefacts
        env:
          FOLDER_URL: https://drive.google.com/drive/u/6/folders/1qMPS1xd8Apkf0WJDlUjA5h7kaQDRDG5N
        run: |
          mkdir -p mlruns
          # --folder  → recursive download
          # --remaining-ok → OK if folder has >50 files (gdow's hard limit)  
          gdown "$FOLDER_URL" \
                --folder \
                --remaining-ok \
                -O mlruns

      - name: Start services via Docker Compose
        run: docker compose up --build -d

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Wait for EEP health endpoint
        run: |
          echo "Checking EEP health status..."
          for i in {1..12}; do
            curl -s http://localhost:8000/health | jq
            if curl -s http://localhost:8000/health | jq -e '.status == "healthy"' >/dev/null; then
              echo "EEP is healthy"
              exit 0
            fi
            echo "Attempt $i: not healthy yet"
            sleep 5
          done
          echo "EEP did not become healthy in time"
          exit 1

      - name: Download test video
        run: |
          echo "Copying test video from demo folder..."
          cp demo/Shoplifting001_x264_9.mp4 test_video.mp4

      - name: Test process-video endpoint
        run: |
          echo "Testing process-video endpoint..."
          response=$(curl -s \
            -F "file=@test_video.mp4" \
            -F "video_id=test_video" \
            http://localhost:8000/process-video)
          echo "Response: $response"
          if echo "$response" | jq -e 'has("shoplifting_detected") and has("video_id")' >/dev/null; then
            echo "Video processing response has expected shape"
            exit 0
          else
            echo "Unexpected video processing result: $response"
            exit 1
          fi

      - name: Stop services
        if: always()
        run: docker compose down
